import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setup(04, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(20, GPIO.OUT)
GPIO.setup(21, GPIO.OUT)
while True:
	GPIO.output(04 ,True)
	time.sleep(.1)
	GPIO.output(16 ,False)
	GPIO.output(20 ,True)
	time.sleep(.1)
	GPIO.output(21 ,False)
	GPIO.output(04 ,False)
	GPIO.output(16 ,True)
	time.sleep(.1)
	GPIO.output(20 ,False)
	GPIO.output(21 ,True)
	time.sleep(.1)
